# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orbs/use/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2

jobs:
  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:8I7Pcgm3a3t7PY9DjbJ6fJtDBso4lDy/CcQdw4K1w/I"

      - run:
          name: Deploy to EC2
          command: |
            ssh ubuntu@ec2-13-222-183-56.compute-1.amazonaws.com "
              cd DevOpsCA &&
              git pull &&
              npm install &&
              pm2 restart all
            "
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm